import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { CartProvider } from "./components/CartContext";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <CartProvider>
          <Suspense fallback={<div className="h-16 border-b bg-white/80 backdrop-blur"></div>}>
            <Navbar />
          </Suspense>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
